services:
  jekyll:
    image: jekyll/jekyll:latest
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    command: >
      sh -c "bundle config set --local path /usr/local/bundle
      && bundle install
      && bundle exec jekyll serve --force_polling --host 0.0.0.0 --baseurl ''"
    working_dir: /srv/jekyll
